# Generated by Django 4.1.3 on 2023-01-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Funcionario', 'Funcionario'), ('Professor', 'Professor')], max_length=100),
        ),
    ]
