# Generated by Django 4.1.3 on 2023-01-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_users_email_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='email_usuario',
            new_name='email',
        ),
    ]
