# Generated by Django 4.1.3 on 2023-01-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_aluno', models.CharField(max_length=256)),
                ('cpf_aluno', models.CharField(max_length=11, unique=True)),
                ('data_nascimento_aluno', models.DateField()),
                ('endereco_aluno', models.CharField(max_length=256)),
                ('email_aluno', models.EmailField(max_length=254)),
                ('turno_aluno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=256)),
                ('arte_marcial_aluno', models.CharField(choices=[('Kung Fu', 'Kung Fu'), ('Karatê', 'Karatê'), ('Judô', 'Judô'), ('Jiu-Jitsu', 'Jiu-Jitsu'), ('Muay Thai', 'Muay Thai'), ('Taekwondo', 'Taekwondo')], max_length=256, null=True)),
            ],
        ),
    ]
