# Generated by Django 4.1.3 on 2023-01-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='arte_marcial_aluno',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno_aluno',
            field=models.CharField(max_length=256),
        ),
    ]
